num1 = int(input("Enter first numver:"))
num2 = int(input("Enter second numver:"))
print("Result:", num1 + num2)
print("Result:", num1 - num2)
print("Result:", num1 * num2)
print("Result:", num1 / num2)